version: "3.9"
services:
  backend:
    image: "backend"
    container_name: "backend"
    ports:
      - "8080:8080"

  frontend:
    image: "frontend"
    container_name: "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend